Rscript --vanilla causal_analyses.R -e 'mean_distance_all_persistent_dealers' -sd 100 -s 'state' -p '5.95'
Rscript --vanilla causal_analyses.R -e 'mean_distance_all_persistent_dealers' -sd 100 -s 'state' -p '1.99'
Rscript --vanilla causal_analyses.R -e 'mean_distance_all_persistent_dealers' -sd 100 -s 'state.urbanicity' -p '5.95'
Rscript --vanilla causal_analyses.R -e 'mean_distance_all_persistent_dealers' -sd 100 -s 'state.urbanicity' -p '1.99'
Rscript --vanilla causal_analyses.R -e 'mean_dist_commercial_dealers' -sd 100 -s 'state' -p '5.95'
Rscript --vanilla causal_analyses.R -e 'mean_dist_commercial_dealers' -sd 100 -s 'state' -p '1.99'
Rscript --vanilla causal_analyses.R -e 'mean_dist_commercial_dealers' -sd 100 -s 'state.urbanicity' -p '5.95'
Rscript --vanilla causal_analyses.R -e 'mean_dist_commercial_dealers' -sd 100 -s 'state.urbanicity' -p '1.99'
