Rscript --vanilla continuous_treatment_causal_analyses.R -e 'mean_distance_all_persistent_dealers' -s 100 -sa 'state' -p '5.95'
Rscript --vanilla continuous_treatment_causal_analyses.R -e 'mean_distance_all_persistent_dealers' -s 100 -sa 'state' -p '1.99'
Rscript --vanilla continuous_treatment_causal_analyses.R -e 'mean_distance_all_persistent_dealers' -s 100 -sa 'state.urbanity' -p '5.95'
Rscript --vanilla continuous_treatment_causal_analyses.R -e 'mean_distance_all_persistent_dealers' -s 100 -sa 'state.urbanity' -p '1.99'
Rscript --vanilla continuous_treatment_causal_analyses.R -e 'mean_dist_commercial_dealers' -s 100 -sa 'state' -p '5.95'
Rscript --vanilla continuous_treatment_causal_analyses.R -e 'mean_dist_commercial_dealers' -s 100 -sa 'state' -p '1.99'
Rscript --vanilla continuous_treatment_causal_analyses.R -e 'mean_dist_commercial_dealers' -s 100 -sa 'state.urbanity' -p '5.95'
Rscript --vanilla continuous_treatment_causal_analyses.R -e 'mean_dist_commercial_dealers' -s 100 -sa 'state.urbanity' -p '1.99'
