---
title: "R Notebook"
output: html_notebook
---


```{r}
#Load packages
library(readxl)
library(data.table)
```

### Import raw data

```{r}
dir <- "../" # run code in the script location
```

```{r}
tracts_2020_all_data <- read_excel(paste0(dir, "data/input/private/tracts_2020_all_data_revised.xlsx"))
tracts_2020_all_data <- as.data.table(tracts_2020_all_data)
tracts_2020_all_data
```

```{r}
census_divisions_data <- fread(paste0(dir, "data/input/open/census_regions_divisions.csv"))
census_divisions_data
```

```{r}
mental_health_data <- fread(paste0(dir, "data/input/private/interpolated_mental_health.csv"))
mental_health_data

```

```{r}
urbanity_data <- fread(paste0(dir, "data/input/open/NCHSURCodes2013.csv"))
urbanity_data <- as.data.table(urbanity_data)
urbanity_data
```

```{r}
codebook <- read_excel(paste0(dir, "data/input/private/codebook_all.xlsx"))
codebook
```

### Merge Datasets 

```{r}
census_divisions_data <- subset(census_divisions_data, select = c("state_fips", "census_division_number"))
census_divisions_data[, state_fips := ifelse(nchar(state_fips) == 1, paste0("0", state_fips), state_fips)] # add leading 0 if necessary, convert state_fips to character
census_divisions_data
```

```{r}
tracts_2020_all_data[, state_fips := substr(GEOID, 1, 2)]
tracts_2020_all_data[, county_fips := substr(GEOID, 1, 5)]
tracts_2020_all_data <- merge(tracts_2020_all_data, census_divisions_data, by = "state_fips", all.x = T, all.y = F)
tracts_2020_all_data
```

```{r}
mental_health_data <- subset(mental_health_data, select = c("GEOID_TXT", "mental_health_index"))
setnames(mental_health_data, "GEOID_TXT", "GEOID")
mental_health_data$GEOID <- as.character(mental_health_data$GEOID)
mental_health_data[, GEOID := ifelse(nchar(GEOID) == 10, paste0("0", GEOID), GEOID)]
mental_health_data
```

```{r}
tracts_2020_all_data <- merge(tracts_2020_all_data, mental_health_data, by = "GEOID", all.x = T, all.y = F)
tracts_2020_all_data
```

```{r}
urbanity_data <- urbanity_data[, .(county_fips = as.character(`FIPS code`), urban_rural = `2013 code`)]
urbanity_data[, county_fips := ifelse(nchar(county_fips) == 4, paste0("0", county_fips), county_fips)]
urbanity_data
```

```{r}
tracts_2020_all_data <- merge(tracts_2020_all_data, urbanity_data, by = "county_fips", all.x = T, all.y = F)
tracts_2020_all_data
```

### Remove rows

```{r}
tracts_2020_subset <- tracts_2020_all_data[!startsWith(GEOID, "72")] # remove Puerto Rico because school shooting dataset (https://www.chds.us/ssdb) doesn't cover PR
tracts_2020_subset
```

```{r}
# checking if Puerto Rico is removed
nrow(tracts_2020_subset[startsWith(GEOID, "72")])
```


```{r}
tracts_2020_subset <- tracts_2020_subset[!is.na(MEAN_Total_Miles_1)] # remove 252 NA's in exposure variable; removes Hawaii
tracts_2020_subset
```
```{r}
#checking if all NAs in 'MEAN_Total_Miles_1' have been removed
nrow(tracts_2020_subset[is.na(MEAN_Total_Miles_1)])
```


```{r}
tracts_2020_subset <- tracts_2020_subset[P0010001 != 0] # remove 18 Census tracts with total population 0
tracts_2020_subset
```
```{r}
#checking if all Tracts with 0 population are removed 
nrow(tracts_2020_subset[P0010001 == 0])
```


```{r}
tracts_2020_subset <- tracts_2020_subset[MEAN_Total_Miles_1 <= 500] # there are 136 tracts with MEAN_Total_Miles_1 >= 500; all other tracts have MEAN_Total_Miles_1 <= 100.21; removes Alaska
tracts_2020_subset
```

```{r}
#checking if Alaska is removed
nrow(tracts_2020_subset[MEAN_Total_Miles_1>500])
```


### Subset columns (aka variables) 

```{r}

all_vars <- setDT(data.frame(var_name = codebook$FieldName, include = as.logical(codebook[[7]])))
include_vars <- all_vars[include == TRUE, var_name]
include_vars
```

```{r}
tracts_2020_subset <- subset(tracts_2020_subset, select = include_vars)
tracts_2020_subset
```
```{r}
#check if all required columns are included
setequal(colnames(tracts_2020_subset), include_vars)
```


### Rename Variables

```{r}
setnames(tracts_2020_subset, old = c("MEAN_Total_Miles_1", "Shape_Area",
                                     "PCT_P0030001", "PCT_P0020005", "PCT_P0020006", "PCT_P0020007", "PCT_P0020008", "PCT_P0020009", "PCT_P0020011", "PCT_P0020002", 
                                     "P0050002", "P0050007",
                                     "householdincome_medhinc_cy", "incomebyage_media15_cy",
                                     "P0010001", "P0030001", "daytimepopulation_dpop_cy", "H0010001", "crime_crmcytotc"),
         new = c("mean_total_miles", "Tract_Area_sq_meters",
                 "pct_18plus", "white_only_pct", "black_only_pct", "american_indian_alaskan_native_only_pct", "asian_only_pct", "native_hawaiian_pacific_islander_only_pct", "multiracial_pct", "hispanic_latino_pct",
                 "institutional_group_pop", "noninstitutional_group_pop",
                 "median_household_inc_2021", "median_household_inc_15to24_2021",
                 "total_population_2020", "pop18plus", "daytime_pop_2021", "total_housing_units", "total_crime_2021"))

tracts_2020_subset
```

### Extract, transform, scale variables

```{r}
tracts_2020_transformed <- copy(tracts_2020_subset)
tracts_2020_transformed[, state_fips := substr(GEOID, 1, 2)]
tracts_2020_transformed[, county_fips := substr(GEOID, 1, 5)]
tracts_2020_transformed[, area_sq_miles := Tract_Area_sq_meters / 1.60934^2]
tracts_2020_transformed[, log_median_hh_income := log(median_household_inc_2021 + 0.01)]
tracts_2020_transformed[, log_median_hh_income_15to24 := log(median_household_inc_15to24_2021 + 0.01)]
tracts_2020_transformed[, `:=`(dealers_per_100_sq_miles = count_gun_dealers/area_sq_miles*100,
                          schools_per_100_sq_miles = count_schools/area_sq_miles*100)]
tracts_2020_transformed
```
```{r}
tracts_2020_transformed[, `:=`(prop_18plus = pct_18plus/100,
                          prop_white_only = white_only_pct/100,
                               prop_black_only = black_only_pct/100,
                               prop_american_indian_alaskan_native_only = american_indian_alaskan_native_only_pct/100,
                               prop_asian_only = asian_only_pct/100,
                               prop_native_hawaiian_pacific_islander_only = native_hawaiian_pacific_islander_only_pct/100,
                               prop_multiracial = multiracial_pct/100,
                               prop_hispanic_latino = hispanic_latino_pct/100)]
tracts_2020_transformed[, `:=`(prop_food_stamps_2019 = foodstampssnap_acssnap_p/100,
                               prop_public_assist_income_2019 = households_acspubai_p/100,
                               prop_below_poverty_2019 = households_acshhbpov_p/100,
                               prop_without_vehicles_2019 = vehiclesavailable_acsoveh0_p/100,
                               prop_hunted_with_shotgun_2021 = sports_mp33018a_b_p/100,
                               prop_bachelor_deg_25plus_2021 = educationalattainment_bachdeg_cy_p/100,
                               prop_grad_deg_25plus_2021 = educationalattainment_graddeg_cy_p/100,
                               prop_unemployed_2021 = employmentunemployment_unemprt_cy/100,
                               prop_unemployed_16to24_2021 = employmentunemployment_unage16cy_p/100)]
tracts_2020_transformed[, `:=`(housing_units_per_100_sq_miles = total_housing_units/area_sq_miles*100,
                               prop_institutional_group = institutional_group_pop/total_population_2020, 
                               prop_noninstitutional_group = noninstitutional_group_pop/total_population_2020)]
tracts_2020_transformed <- tracts_2020_transformed[, `:=`(Tract_Area_sq_meters = NULL, median_household_inc_2021 = NULL, median_household_inc_15to24_2021 = NULL,
                                                          pct_18plus = NULL, white_only_pct = NULL, black_only_pct = NULL, american_indian_alaskan_native_only_pct = NULL,
                                                          asian_only_pct = NULL, native_hawaiian_pacific_islander_only_pct = NULL, multiracial_pct = NULL,
                                                          hispanic_latino_pct = NULL, foodstampssnap_acssnap_p = NULL, households_acspubai_p = NULL,
                                                          households_acshhbpov_p = NULL, vehiclesavailable_acsoveh0_p = NULL, sports_mp33018a_b_p = NULL,
                                                          educationalattainment_bachdeg_cy_p = NULL, educationalattainment_graddeg_cy_p = NULL,
                                                          employmentunemployment_unemprt_cy = NULL, employmentunemployment_unage16cy_p = NULL,
                                                          total_housing_units = NULL, institutional_group_pop = NULL, noninstitutional_group_pop = NULL)]

tracts_2020_transformed
```



