Rscript --vanilla matching_without_covariates_for_evalue.R -c 'demographic'
Rscript --vanilla matching_without_covariates_for_evalue.R -c 'socioeconomic'
Rscript --vanilla matching_without_covariates_for_evalue.R -c 'mental_health'
Rscript --vanilla matching_without_covariates_for_evalue.R -c 'crime'
Rscript --vanilla matching_without_covariates_for_evalue.R -c 'gun_affinity'
Rscript --vanilla matching_without_covariates_for_evalue.R -c 'racioethnic'
